language: c
branches:
  only:
    - cmake
env:
  - CFLAGS="-m32"
  - CFLAGS="-m64"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6:i386 libgcc1:i386 gcc-4.6-base:i386 gcc-multilib
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
