language: c
branches:
  only:
    - cmake
env:
  - CFLAGS="-m32"
  - CFLAGS="-m64"
before_script:
  -  if [[ "$CFLAGS" == "-m32" ]]; then sudo apt-get update -qq; fi
  -  if [[ "$CFLAGS" == "-m32" ]]; then sudo apt-get install -y libc6:i386 libgcc1:i386 gcc-4.6-base:i386 gcc-multilib libssl-dev:i386; fi
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
