version: "{build}"

branches:
  only:
  - master

platform:
  - x64
  - x86

build_script:
  - mkdir build
  - cd build
  - if %PLATFORM% == x86 cmake .. -G "Visual Studio 14 2015"
  - if %PLATFORM% == x64 cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build .
